name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: .
      - name: Update diagram
        id: make_diagram
        uses: githubocto/repo-visualizer@0.7.1
        with:
          output_file: "output-diagram.svg"
          artifact_name: "diagram"
      - name: Get artifact
        uses: actions/download-artifact@v2
        with:
          name: "diagram"
          path: "downloads"
          should_push: false
